sonar.projectKey=com.hobsojam.simpleestimation
sonar.projectName=Simple Estimation Android

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java
sonar.sourceEncoding=UTF-8

sonar.coverage.jacoco.xmlReportPaths=app/build/reports/coverage/test/debug/report.xml
sonar.sarifReportPaths=app/build/reports/detekt/detekt.sarif
sonar.androidLint.reportPaths=app/build/reports/lint-results-debug.xml
