config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true

style:
  MagicNumber:
    active: true
    ignoreAnnotated:
      - Composable
  MaxLineLength:
    active: true
    maxLineLength: 120
  WildcardImport:
    active: true

complexity:
  LongMethod:
    active: true
    allowedLines: 80
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 10

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable

potential-bugs:
  active: true
